### ISSUE TITLE
Cloud annotations: Handle invalid bucket objects gracefully 

### ISSUE THREAD

**Issue by ptitzler** [cloud-annotations/cloud-annotations#162]
Recreate steps:
- upload a file that is not a properly encoded JPG/PNG image to a COS bucket
- In cloud annotations select the bucket and annotation type "localization"

Result:
- A generic file icon is displayed in the carousel but no error is displayed.
- One can draw a bounding box in the editor

Expected result:
- The user is notified that one or more objects in the bucket are not of the support type.
- The user can somehow identifye which objects are problematic.
- The use cannot annotate the objects in the editor.

**Comment by bourdakos1** [comment]
I'm working on some updates to cloud annotations, does this look like it addresses your issue?
<img width="1904" alt="Screen Shot 2020-11-16 at 2 40 46 PM" src="https://user-images.githubusercontent.com/4212769/99300064-1fa37980-281a-11eb-9b67-57b14ab6123c.png">

**Comment by ptitzler** [comment]
Yep!
