### ISSUE TITLE
not able to install cacli windows

### ISSUE THREAD

**Issue by delrio499** [cloud-annotations/cloud-annotations#207]
So i'm trying to install cacli for my image recognition, and i'm not able to. i changed the name, add it to the PATH and tried to install it from command line but well i don't see anything happening. I'm struggling with this situation bc i don't know much about cloud annotation or ibm. i'm following this tutorial https://www.youtube.com/watch?v=ijbbPT1NBl4&t=1395s  but a lot of things have changed so i'm trying to do it as i can, i'm from colombia so english is not my first lenguage. i'm new to a lot of things...
this is where i'm trying to install it 
![Capture](https://user-images.githubusercontent.com/52754394/76377420-dc068080-6318-11ea-807d-361c1f578a76.PNG)

and this is the PATH i created

![capture2](https://user-images.githubusercontent.com/52754394/76377500-107a3c80-6319-11ea-8484-7ad60df1f542.PNG)

and bc it says that i need to install it from the cmd i am trying to do it like this 
C:\Users\Arturo\imagerec> start cacli.exe
and then i don't see anything happen
 pls somebody help me :(

**Comment by delrio499** [comment]
so i realized that there is the repository if i download it and save it in the folder would that do the trickxd? like is that enough?

**Comment by delrio499** [comment]
i tried to install it from scoop and it says "couldn't find manifest for 'cacli.exe'"

**Comment by bourdakos1** [comment]
Cacli isn’t available on scoop (I’m not sure how to get it on scoop) you should just be able to run “cacli” from the command line. Shouldn’t have to run “start cacli.exe”
