### ISSUE TITLE
train process is pending in cloud

### ISSUE THREAD

**Issue by mas1515** [cloud-annotations/cloud-annotations#216]
Hello  @bourdakos1 
i use cloud train button  in  https://cloud.annotations.ai/training
but it stopped in pending status after 1 day 
what shoud i do ??

see  this picture 

[https://pasteboard.co/Ji2aruH.png]
(https://pasteboard.co/Ji2aruH.png)

**Comment by bourdakos1** [comment]
I think too many people have been using the gpus the last couple days

**Comment by mas1515** [comment]
@bourdakos1 

How long may it take
Until it's my turn to start process ??

**Comment by bourdakos1** [comment]
no idea, sorry :(

**Comment by mas1515** [comment]
@bourdakos1  
ok thank you 

i test google colab solution

but i get this error 

can you help me ???


https://pasteboard.co/JitWvm8.png

in  Model config section

**Comment by bourdakos1** [comment]
I think the “ssd_mobilenet....” Variable needs do be in quotes to make it a string

**Comment by bourdakos1** [comment]
Oh yea I thats a typo, I think that variable was supposed to be this: `CONFIG_TYPE`

Which is defined at the top of the notebook and is just the “ssd_mobilenet_v1_quantized_....._sync” string

**Comment by bourdakos1** [comment]
I updated the notebook to fix the issue

**Comment by mas1515** [comment]
@bourdakos1 

thank for response 
i check  notebook and it works  
but we have many different 

1- after i exported  create as ml
my folder has 444 picture But i uploaded 1250 picture to cloud and annotate all of them (1250)
why this happend ??

2- after training in colab model_web folder has 2 .bin file (like image) 

https://pasteboard.co/JiDlLnz.png


but in GUI cloud training after i download model_web 
i have 4 .bin file in model_web(like image)
https://pasteboard.co/JiDmgFj.png

3- after that i test model_web But it's accuracy is very low with false detection  
how resolve this problem ??

**Comment by bourdakos1** [comment]
Sorry I missed this, is this still an issue?
