### ISSUE TITLE
Cloud Annotations not working with new Watson v4?

### ISSUE THREAD

**Issue by weritmedal** [cloud-annotations/cloud-annotations#219]
Using the production version of Cloud Annotations, https://cloud.annotations.ai/,  I am unable to train models or even view the training runs page.  There are all sorts of 40X errors like:  

api/proxy/us-south.ml.cloud.ibm.com/v3/models:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

When trying to train a model, there are errors like:

/api/proxy/us-south.ml.cloud.ibm.com/v3/ml_assets/training_definitions:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

I am able to use the production site fine otherwise, just issues when doing the training and viewing the training runs. 

Is it updated to use the new V4 version they mentioned in the update?

**Comment by bourdakos1** [comment]
Do you know when watson machine learning updated to v4?

**Comment by weritmedal** [comment]
Watson Machine Learning Service rolls out new plan
Component: Machine Learning
Location: Asia Pacific, Europe, North America
Start time: 1 Sep 2020, 12:07 PM
Update time: 1 Sep 2020, 4:37 PM
Severity: Major impact

https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/whats-new.html

**Comment by bourdakos1** [comment]
Thank you this is extremely helpful

**Comment by weritmedal** [comment]
You're welcome.  Is there any workaround or am I out of luck using Cloud Annotations for a while?

**Comment by bourdakos1** [comment]
I'm not sure, the new v4 stuff is news to me haha. I'll take today to look over and try to migrate. It seems like training is still working for me. Do you have an old instance of WML or did you create it after september 1st?

**Comment by weritmedal** [comment]
I tried the older one, this morning and didn't have any luck so I deleted it.  The new one I created today.  

When I use cacli list, I get:

error Unable to get /v3/wml_instances/21b29fac-d0b1-47d8-8116-0343af5ad944 [400]: {"trace":"9f0f3af31cf0fcf8df44aa77d48439ad","errors":[{"code":"invalid_request","message":"Instance in v2 plan should use v4 API."}]}

**Comment by weritmedal** [comment]
This may or may not be related, but I cannot create new credentials for the WML instance.  It throws an error that says the service broker returned 400.  I opened a ticket with IBM.

**Comment by bourdakos1** [comment]
Okay yea it looks like the “v2” instances will only work with “wml v4”, and all lite tier instances automatically upgraded to “v2”. The instance I’m using is a paid tier so it’s still able to use “wml v3”

Service credential wise, I think I read something that said wml doesn’t use iam credentials at a service level anymore, but at a spaced level? Not sure...

**Comment by weritmedal** [comment]
I am using a paid instance of ML as well.  I had started with Lite, but the new instance is V2 Standard.

**Comment by bourdakos1** [comment]
yea you can no longer prevision a v1 instance

I'm not able to generate service credentials for my v2 instance either

**Comment by weritmedal** [comment]
I guess that would explain why training is failing for me if there are no Writer credentials.

**Comment by bourdakos1** [comment]
from the [migration guide](https://dataplatform.cloud.ibm.com/docs/content/DO/WML_Deployment/MigrationWMLAPIV4Beta.html):
"Authorization has now been simplified. Obtaining bearer tokens from IAM is now performed using a generic user apikey instead of a Watson Machine Learning specific apikey. It is no longer necessary to create specific credentials on the Watson Machine Learning instance."

**Comment by bourdakos1** [comment]
looks like v4 is **very** different from v3, this might take a while...

**Comment by weritmedal** [comment]
So old instances are still ok, but new instances are incompatible at the moment?

**Comment by bourdakos1** [comment]
if the old instance is a paid tier, it's still okay. If it's a new instance or an old lite tier, it's incompatible at the moment

**Comment by weritmedal** [comment]
Ah.  Thanks for checking into it.  Please let me know if you need help testing the V4 update.

**Comment by chrisesharp** [comment]
I'm using a free Lite tier, and I get the same problem....although it is reporting in the error that I am using a V2 plan, which is not the case.

**Comment by bourdakos1** [comment]
All lite tier service instances were auto-migrated to v2

**Comment by bourdakos1** [comment]
due to unresolved issues on the watson machine learning side, I won't be pursing this anytime soon
