### ISSUE TITLE
Unknow tensor shape

### ISSUE THREAD

**Issue by quangArchiviet** [cloud-annotations/cloud-annotations#235]
Hi guys,
After trained object detection model on Colab, i use **coremltools** to convert **frozen_inference_graph.pb** to **.mlmodel** ... but got error when trying to set **ouputs** with tensor have **unknow** shape.

**- detection_boxes**
**- detection_scores**
**- detection_classes**

```
TensorFlow version 1.15.0
Eager mode:  False
Is GPU available:  True
Inputs ops: 
op name: image_tensor, output shape : (?, ?, ?, 3)

Prospective output tensor(s): 
tensor name: Preprocessor/map/while/Switch:0, tensor shape : <unknown>, parent op type: Switch
tensor name: Preprocessor/map/while/Switch_1:0, tensor shape : <unknown>, parent op type: Switch
tensor name: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Switch:0, tensor shape : <unknown>, parent op type: Switch
tensor name: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Switch_1:0, tensor shape : <unknown>, parent op type: Switch
tensor name: detection_boxes:0, tensor shape : <unknown>, parent op type: Identity
tensor name: detection_scores:0, tensor shape : <unknown>, parent op type: Identity
tensor name: detection_multiclass_scores:0, tensor shape : <unknown>, parent op type: Identity
tensor name: detection_classes:0, tensor shape : <unknown>, parent op type: Identity
tensor name: num_detections:0, tensor shape : <unknown>, parent op type: Identity
tensor name: raw_detection_boxes:0, tensor shape : (?, ?, 4), parent op type: Identity
tensor name: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/SortByField/TopKV2:0, tensor shape : (?,), parent op type: TopKV2
tensor name: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/SortByField_1/TopKV2:0, tensor shape : (?,), parent op type: TopKV2
tensor name: raw_detection_scores:0, tensor shape : (?, ?, 14), parent op type: Identity
```

`ValueError: Op Postprocessor/Tile (Tile) type inference ([is34, is35, is36]) and TF output shape ([-1, 1917, 4]) mismatch`

**Comment by bourdakos1** [comment]
Converting the object detection model to Core ML is a bit tricky, because you need to strip certain ops out of the graph before converting and then reconstruct them in app code.

If you look in this repo there are some conversion scripts that does all of this

**Comment by bourdakos1** [comment]
Here’s were all the conversion scripts live: 
https://github.com/cloud-annotations/training/tree/master/trainer/src/convert

**Comment by quangArchiviet** [comment]
@bourdakos1 thanks you so much for reply quickly ...
I tried this solution before but always got **ValueError: Graph has cycles**


`/usr/local/lib/python3.6/dist-packages/tfcoreml/_tf_graph_transform.py in _push_stack(stack, node, in_stack)
     36   stack.append(node)
     37   if node in in_stack:
---> 38     raise ValueError('Graph has cycles.')
     39   else:
     40     in_stack[node] = True

ValueError: Graph has cycles.`

**Comment by bourdakos1** [comment]
The cycles should be removed if using the above scripts, do you mind sharing your code?

**Comment by quangArchiviet** [comment]
> The cycles should be removed if using the above scripts, do you mind sharing your code?

Maybe I made mistakes somewhere. Thank you for your help 👍 

https://colab.research.google.com/drive/1pqtoma05uy4DYuzmsZCnxPAwZgGGTjY5#scrollTo=GmloKE6Qx8Lu

**Comment by bourdakos1** [comment]
Oh maybe it's because the other training script uses `ssd_mobilenet_v1_coco_2018_01_28` and colab uses `ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18`, perhaps the input/output names have changed

**Comment by bourdakos1** [comment]
if you share the frozen_inference_graph.pb, I can try and find the right input/outputs

**Comment by quangArchiviet** [comment]
Got same error with **ssd_mobilenet_v1_coco_2018_01_28**

```
MODEL_TYPE = 'ssd_mobilenet_v1_coco_2018_01_28'
CONFIG_TYPE = 'ssd_mobilenet_v1_coco'
```


**Export inference graph** step
```
======================End of Report==========================
132 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.
```

The notebook URL I shared with you above have a real config (annotations bucket), so you can run it to train 
[frozen_inference_graph.pb.zip](https://github.com/cloud-annotations/training/files/5540057/frozen_inference_graph.pb.zip)
the model

**Comment by bourdakos1** [comment]
thank you, I'll try it out!

**Comment by bourdakos1** [comment]
Sorry I haven’t had a chance to work this out yet...

**Comment by bourdakos1** [comment]
How many images and labels do you have?
