### ISSUE TITLE
Feature Request: Simple keyboard commands

### ISSUE THREAD

**Issue by devandanger** [cloud-annotations/cloud-annotations#261]
It would help to have some simple keyboard commands in order to do the following.

Keyboard command to toggle from creating object detection rectangle and modifying the rectangle.
Keyboard command to move context from the image to the image lists.

**Comment by bourdakos1** [comment]
If you hold the CTRL key (CMD on Mac) it will toggle to the modify mode while holding

**Comment by devandanger** [comment]
wow thanks!
