### ISSUE TITLE
Make cacli trained models deployable with ibmcloud cli

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/cloud-annotations#45]

**Comment by bourdakos1** [comment]
Not sure if this works or not

**Comment by bourdakos1** [comment]
run this to store the model:
```
bx ml store training-runs model-frkjjejs
```

You get this output:
```
Starting to store the training-run 'model-frkjjejs' ...
OK
Model store successful. Model-ID is '18510cf7-2a9b-4677-9280-b4604e2e10cb'.
```

**Comment by sachinshelke** [comment]
Hi @bourdakos1 ,

Did you upgrade TensorFlow Version from 1.12 to 1.13?

**Comment by bourdakos1** [comment]
Uh i dont think i have yet

**Comment by bourdakos1** [comment]
After much thought, I don't think we will add `cacli deploy MODEL_ID` to the cli. It opens a whole can of worms for actually managing the deployments. However, we will have support for deploying cacli trained models via the ibmcloud cli

**Comment by bourdakos1** [comment]
```
ibmcloud ml store training-runs model-rzx3e1hp 
```
```                                               
Starting to store the training-run 'model-rzx3e1hp' ...
OK
Model store successful. Model-ID is '24b55363-5e5a-49d6-8e27-cb39848d2290'.
```

**Comment by bourdakos1** [comment]
The issue
```
Status             DEPLOY_FAILURE   
error code         load_model_failure   
error message      SavedModel file does not exist at: /opt/ibm/scoring/python/workdir/tf_model_9982583f006a48e51f639af3d6de2d7f_L7PeAQATO0/{saved_model.pbtxt|saved_model.pb} 
```

**Comment by libardolara** [comment]
is there any workaround or doc to deploy the model to WML?

**Comment by bourdakos1** [comment]
@libardolara  deploying to WML should work now, let me see if I have any instructions

**Comment by libardolara** [comment]
I've tried 

`ibmcloud ml store training-runs model model-jok9rswi`
but got 
`Could not read the following file 'model-jok9rswi'.`

**Comment by bourdakos1** [comment]
I think you need to find the training run id

**Comment by bourdakos1** [comment]
just kidding try:

```
ibmcloud ml store training-runs model-jok9rswi
```

**Comment by libardolara** [comment]
Ty, rookie mistake on my part! deployed successfully
