### ISSUE TITLE
Add support for more flexible object detection model selection (quantized, faster-rcnn, etc...)

### ISSUE THREAD

**Issue by hunterjm** [cloud-annotations/cloud-annotations#49]
I stumbled upon this project from a LinkedIn post, and it peeked my interest as I've implemented a TensorFlow component in [Home Assistant](https://www.home-assistant.io/components/tensorflow/), a popular open source home automation platform.

One of the requests I get frequently is the ability to train and use custom object labels.  Up to this point, I've told people that the effort required to do so is too great for most users.

On to the feature request... I noticed [here](https://github.com/cloud-annotations/training/blob/master/trainer/src/data/prepare_data_object_detection.py#L156) that you are defaulting the model to an SSD MobileNet model.  How large is the effort to allow users to choose the base model to train?  I, for example, am using the `faster_rcnn_inception_v2_coco` model since the SSD model is not accurate enough for the distance and angle of the cameras I have mounted.

**Comment by bourdakos1** [comment]
It shouldn’t be too difficult to add this. At the moment you can actually provide your own training zip. So instead of running `cacli train` Try running `cacli train path_to_zip`

**Comment by hunterjm** [comment]
Thanks for the quick reply.  Can you give me some quick pointers as to what would need to change in the training folder?  Would it simply be to link to a different model, or will I need to modify the training `pipeline.config` file as well?  Any outline would be appreciated.

**Comment by bourdakos1** [comment]
You would need to modify which checkpoint is being downloaded in the data prep script and you would need to grab the corresponding pipeline.config. Run `python setup.py all` which will clone the TensorFlow object detection api repo. Then after you finish making all the necessary changes run that same command again to generate the training.zip

**Comment by bourdakos1** [comment]
Another thing to note, is that the core ml/tflite conversions won’t work anymore, they are only compatible with ssd at the moment

**Comment by hunterjm** [comment]
I will play around with it.  If it’s something you would like to support as a configuration option in the future, I’ll leave this issue open and possibly take a stab at implementing if you haven’t gotten to it by then.

**Comment by bourdakos1** [comment]
That would be great :)

**Comment by husnejahan** [comment]
hi,
I am getting this error"(Using settings from config.yaml)
error Invalid Cloud Object Storage credentials."
how to change or start process again
