### ISSUE TITLE
[CLI] Add picker support for non-TTY terminals like gitbash 

### ISSUE THREAD

**Issue by OlteanuRadu** [cloud-annotations/cloud-annotations#53]
Using the cacli I was able to connect to the ML IBM service and to the Object Storage. After this I can see my bucket name, but I dont know how to continue this process, it says Use arrow keys .. but it's not doing anything. 

Please see the attached photo 
![image](https://user-images.githubusercontent.com/6471559/56357975-e7732980-61e5-11e9-80c9-4f782653770e.png)

**Comment by bourdakos1** [comment]
Does it allow you to hit the enter key to choose the bucket?

**Comment by OlteanuRadu** [comment]
Hi,

When I hit enter, nothing fancy going on, it just enters a new line on the terminal.

Please see the screenshot : 

![image](https://user-images.githubusercontent.com/6471559/56358217-b1827500-61e6-11e9-8402-25d925aa4261.png)

**Comment by bourdakos1** [comment]
Hmm okay, definitely a bug. Do you mind telling me what OS you’re on, and what terminal you’re using?

**Comment by OlteanuRadu** [comment]
Hi,

OS : 

WindowsProductName    WindowsVersion OsHardwareAbstractionLayer
------------------    -------------- --------------------------
Windows 10 Enterprise 1809           10.0.17763.404  


And terminal : 
(2.21.0) 64-bit version of Git for Windows

**Comment by bourdakos1** [comment]
Okay cool, do you mind trying to run it in the regular windows terminal to see if that works?

**Comment by OlteanuRadu** [comment]
Hi,

using windows cmd I was able to train my model, so I suppose that there's a problem with the Git for Windows terminal.

**Comment by bourdakos1** [comment]
Okay I’m reading that git bash isn't a TTY terminal, so It doesn’t support the interactive features. I can try to detect this and provide a different input option

**Comment by pragyakirti** [comment]
Hi, 
I am facing the same issue. After connecting to the ML and Object storage authentication, I see my bucket name. But I am not able to select that bucket. I am using OS version 10.10.5 and Terminal version 2.5.3 (343.7)

**Comment by bourdakos1** [comment]
@pragyakirti Are you using git bash?

**Comment by bourdakos1** [comment]
A possible work around is to preempt commands with `winpty` e.g. `winpty cacli init`, `winpty cacli train`, etc...

See: https://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/
