### ISSUE TITLE
[Trainer] Add support for multibyte characters, like emojis and Chinese/Japanese/Korean

### ISSUE THREAD

**Issue by Unyxos** [cloud-annotations/cloud-annotations#67]
Hello!

I tried to train while my labels were emojis but after some time, the training failed with this error:
`UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f91a' in position 0: ordinal not in range(256)`

I tried to browse through the files to see if there was an option to change from latin-1 to utf-8 but couldn't find anything...

did someone encoutered the same issue and managed to fix it ?
thanks!

**Comment by bourdakos1** [comment]
Oh I think the problem is probably that you tried to use actual emojis as labels. I think the tool supports it but I don't this it's supported in training

**Comment by Unyxos** [comment]
Haa correct that’s what I did ! It’s not a big deal anyway :)

**Comment by bourdakos1** [comment]
We should at least replace non-latin-1 chars with a `?` or something so it doesn't  crash the trainer.
